### ISSUE TITLE
column name "pop"

### ISSUE THREAD

**Issue by codeandstats** [jstaf/gapminder#1]
Thanks a lot for providing the gapminder data as a library, this is quite convenient.
I used this dataset just after teaching my students that they could freely choose between two ways of selecting columns, e.g. `gapminder.year` or `gapminder["year"]`. And of course, they applied the same logic to the column "_pop_" and ran into a host of error messages because of the built-in method `.pop`. 

So I would suggest to maybe change that column name to sth. less ambiguous?

Thanks!

**Comment by jstaf** [comment]
This is going to sound weird, but I think this is sort of a blessing in disguise for your students. This is a very good opportunity to teach students the difference between the two methods of accessing columns and why the `.pop` method of selecting columns can be ambiguous, and why in some cases you might need to "clean" data beforehand. 

In either case, this was meant to be an exact copy of the R teaching dataset (https://jennybc.github.io/gapminder/articles/gapminder.html), so I'm leaving it as-is for now.
